version: '3.8'

services:
  lopez:
    image: ${IMAGE_NAME:-ghcr.io/alisson714/lopez:1.0.5}
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lopez.rule=Host(`lopez.byronrm.com`)"
        - "traefik.http.routers.lopez.tls=true"
        - "traefik.http.routers.lopez.tls.certresolver=letsencrypt"
        - "traefik.http.services.lopez.loadbalancer.server.port=5000"

networks:
  web:
    external: true